### ISSUE TITLE
Plugin doesn't work in latest 1.0.1 Homebridge

### ISSUE THREAD

**Issue by joberembt** [Danimal4326/homebridge-ecoplug#20]
I updated to the latest homebridge this morning, and now I'm stuck in a boot loop with the following error:
 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 69970a61-9dd6-4563-93c5-d66e6857cc37
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:396:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

I tracked down that UUID and it's for the ECO-Plug module - I'm not sure why it's suddenly doing this, I've been running 0.60 on the 0.4.53 version of homebridge for a while now with no issues. I don't know that it makes a difference, but I have 2 plugs, they both previously showed up fine.

Tried removing from config.json and removing the module, and no luck getting back to a working install.

**Comment by joberembt** [comment]
Cleared the accessory cache, and reinstalled and now it seems to be fine.

**Comment by donavanbecker** [comment]
this is because the plugin was once registered as `ecoplugs` and now is registered as ecoplug. Homebridge v1.0.0 doesn't look at the old registred plugin name.
