### ISSUE TITLE
Ecoplug is slowing down my homebridge drastically

### ISSUE THREAD

**Issue by TheTherminator** [Danimal4326/homebridge-ecoplug#8]
Hi Danimal4326,

first: Thank you so much for this amazing plugin! Finally a way to implement affordable devices in Homekit.

Unfortunately the plugin is sometimes slowing down my homebridge drastically; even though that it's running on a high power Linux machine. (Happens when one plug is not responding)

Already tried to change the values of:
this.cache_timeout = 10; // seconds
setInterval(that.devicePolling.bind(that), this.cache_timeout * 1000);
setInterval(that.deviceDiscovery.bind(that), this.cache_timeout * 6000);

but it does not seem to help. 

Any ideas? Thank you very much in advance!

**Comment by NorthernMan54** [comment]
How many of eco devices do you have?

**Comment by TheTherminator** [comment]
thank you for the fast response. I have 4 plugs ... here is the log:

[12/28/2017, 2:47:32 PM] [EcoPlug] Poll: ECO-780483DB Fountain
[12/28/2017, 2:47:32 PM] [EcoPlug] Poll: ECO-78094EB9 Fireplace Livingroom
[12/28/2017, 2:47:32 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:32 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:32 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:32 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:33 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:33 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:52 PM] [EcoPlug] Poll: ECO-780483DB Fountain
[12/28/2017, 2:47:52 PM] [EcoPlug] Poll: ECO-78094EB9 Fireplace Livingroom
[12/28/2017, 2:47:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:53 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:47:53 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:12 PM] [EcoPlug] Poll: ECO-780483DB Fountain
[12/28/2017, 2:48:12 PM] [EcoPlug] Poll: ECO-78094EB9 Fireplace Livingroom
[12/28/2017, 2:48:12 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:12 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:12 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:12 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:13 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:13 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:32 PM] [EcoPlug] Poll: ECO-780483DB Fountain
[12/28/2017, 2:48:32 PM] [EcoPlug] Poll: ECO-78094EB9 Fireplace Livingroom
[12/28/2017, 2:48:32 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:32 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:33 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:33 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:33 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:33 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:52 PM] [EcoPlug] Sending device discovery message
[12/28/2017, 2:48:52 PM] [EcoPlug] Poll: ECO-780483DB Fountain
[12/28/2017, 2:48:52 PM] [EcoPlug] Poll: ECO-78094EB9 Fireplace Livingroom
[12/28/2017, 2:48:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:52 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:53 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:53 PM] [EcoPlug] Status: ECO-78094EB9 Fireplace Livingroom is: OFF
[12/28/2017, 2:48:53 PM] [EcoPlug] Adding discovered devices
[12/28/2017, 2:48:53 PM] [EcoPlug] Skipping existing device ECO-78094EB9
[12/28/2017, 2:48:53 PM] [EcoPlug] Skipping existing device ECO-780483DB
[12/28/2017, 2:48:53 PM] [EcoPlug] Adding: ECO-78074DD0 Den Fireplace 192.168.1.65
[12/28/2017, 2:48:53 PM] [EcoPlug] Getting Status: ECO-78074DD0 Den Fireplace
[12/28/2017, 2:48:53 PM] [EcoPlug] Not found  ECO-78076FFB
[12/28/2017, 2:48:53 PM] [EcoPlug] Discovery complete

**Comment by NorthernMan54** [comment]
Tks for the log

The slow response times when one device is missing is a known issue, and I have a fix for it.   I have been running the fix for a few months, and just need to package it up for general use.  Give me a day or 2

**Comment by TheTherminator** [comment]
Fantastic! Thank you so much, I really appreciate it! 

Best,
Stephan

On Dec 28, 2017, at 16:41, NorthernMan54 <notifications@github.com> wrote:

Tks for the log

The slow response times when one device is missing is a known issue, and I have a fix for it. I have been running the fix for a few months, and just need to package it up for general use. Give me a day or 2

**Comment by NorthernMan54** [comment]
Try this version

npm install https://github.com/NorthernMan54/homebridge-ecoplug <https://github.com/NorthernMan54/homebridge-ecoplug>

**Comment by TheTherminator** [comment]
wow that was fast, thank you ... unfortunately the following error when I start homebridge:

[12/29/2017, 2:15:14 PM] ---
[12/29/2017, 2:15:14 PM] ====================
[12/29/2017, 2:15:14 PM] ERROR LOADING PLUGIN homebridge-ecoplug:
[12/29/2017, 2:15:14 PM] Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ecoplug/index.js:12:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
[12/29/2017, 2:15:14 PM] ====================

**Comment by NorthernMan54** [comment]
Looks like the install didn’t go right

Try

sudo npm install -g https://github.com/NorthernMan54/homebridge-ecoplug <https://github.com/NorthernMan54/homebridge-ecoplug>


PS I had the same issue and had fixed it months ago, just never published it

**Comment by TheTherminator** [comment]
OMG YOU ARE A LIFE SAVER!!! It works like a charm now :) Thank you so so much! Do you have a Patreon Page or something, so that I can show my appreciation? 

Here is my log (I removed one device since it was out of reach of my wifi extender)

[12/29/2017, 2:22:14 PM] [EcoPlug] Updating IP Address for ECO-780483DB Fountain 192.168.1.226
[12/29/2017, 2:22:14 PM] [EcoPlug] Updating IP Address for ECO-78076FFB Detached Garage  192.168.1.212
[12/29/2017, 2:22:14 PM] [EcoPlug] Updating IP Address for ECO-78074DD0 Den Fireplace 192.168.1.251

**Comment by Danimal4326** [comment]
@NorthernMan54 I've made you a collaborator in my repo.  If you want to merge your changes, I can publish to NPM

**Comment by NorthernMan54** [comment]
@Danimal4326 Tks I just merged my changes in.  If you could publish, much appreciated.

**Comment by Danimal4326** [comment]
@NorthernMan54 Thanks. Bumped version and published to npm
